services:
  - type: web
    name: job-board-backend
    env: node
    plan: free
    buildCommand: |
      npm install
      npx prisma generate
      npx prisma migrate deploy
    startCommand: node server.cjs
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: job-board-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

databases:
  - name: job-board-db
    plan: free
    ipAllowList: [] # allow all connections
